export const GET_CHARACTERS_REQUESTED = 'GET_CHARACTERS_REQUESTED';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_FAILED = 'GET_CHARACTERS_FAILED';
export const GET_EPISODES_REQUESTED = 'GET_EPISODES_REQUESTED';
export const GET_EPISODES_SUCCESS = 'GET_EPISODES_SUCCESS';
export const GET_EPISODES_FAILED = 'GET_EPISODES_FAILED';